### ISSUE TITLE
Support for Harvester demo?

### ISSUE THREAD

**Issue by neuromancer** [IcePanorama/HarvesterHarvester#1]
I'm wondering if there is support for extracting [demo files](https://archive.org/details/Harvester_demo).

**Comment by IcePanorama** [comment]
Hey! Thanks for the question. Short answer, yes.

Longer answer:
So basically, this program works in two steps under normal usage: first, it extracts a file system from `HARVEST.DAT`, `HARVEST3.DAT`, and `HARVEST4.DAT`--this file system is essentially the original disk images that would've been shipped with the game. And second, it moves into each of these newly extracted file systems and extracts data from the various DAT files that are in there.

Just from taking a quick look at the ISO file, I can tell that this first step won't be necessary, but the second step should be able to function normally without any issues. It's not really well documented at the moment, but there already is a command line argument to skip the first step of this process and go directly to the second (currently, it's `-i`, but that'll likely change).

That being said, that second step isn't done yet, but that'll hopefully be ready within the next week or two. That'll also be the big v1.0.0 release, so you should hopefully get notified when that's out.

Cheers,
-IP
